### ISSUE TITLE
Login System with devise and omniauth

### ISSUE THREAD

**Issue by Salanoid** [Salanoid/octo-swot#1]
I think that app needs a login system. Just users are allow to create swot_tables.

**Comment by cyrilferte** [comment]
Yes, use Devise (https://github.com/plataformatec/devise)

**Comment by Salanoid** [comment]
Yes and omniauth for facebook, twitter, github integrations.

**Comment by Salanoid** [comment]
I'll do that later xD.

**Comment by cyrilferte** [comment]
I added devise and devise architecture, you need to db:migrate on heroku

**Comment by Salanoid** [comment]
I added to on my local machine HAHA, you commited faster than me :+1:
