### ISSUE TITLE
Swot pdf export

### ISSUE THREAD

**Issue by Salanoid** [Salanoid/octo-swot#3]
I think it will be nice if every user has just privates swots but can export them in pdf format. What do you think?

**Comment by cyrilferte** [comment]
good id ! I try many pdf gem for a other project I think the best is 'wicked_pdf' you do the job or I ?

**Comment by Salanoid** [comment]
I can do that job in a few hours or tomorrow. You can do that if you want. I think users should export the views/swot_tables/show.html.erb to a pdf file. Today I made site responsive and I checked it on some tablets and phones.

**Comment by Salanoid** [comment]
Foo commits are for deployment or for setting up things becuase I had some troubles today. Now everything it's good.

**Comment by Salanoid** [comment]
I'm working on that right now.
